[profile.default]
libs = ["lib"]
out = "out"
src = "src"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  '@chainlink/contracts-ccip/=lib/ccip/contracts/',
  '@chainlink/contracts/=lib/chainlink/contracts/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@chainlink/local/=lib/chainlink-local/',
]

# solc = '0.8.20'
evm_version = 'paris'

[rpc_endpoints]
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
